# Generated by Django 5.2.7 on 2026-05-26 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0003_add_ticker_to_portfolio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="ticker",
            field=models.CharField(default="UNKNOWN", max_length=20),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="portfolio",
            constraint=models.UniqueConstraint(
                fields=("user", "ticker"), name="unique_user_ticker"
            ),
        ),
    ]
